table AMZN
	lineageTag: 6f9fb179-0eac-43f3-9b45-24b77b412ef0

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ee051e9-e96f-4654-9392-496b4f361f09
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 6d49a968-2ef8-4624-954e-0f3a0f1866f8
			defaultHierarchy: LocalDateTable_1992af7c-31a0-4345-abd7-318321fbd667.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: c0eaab84-6182-4dcb-a97a-0be8144847fe
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 8748c50c-fe79-40d0-8593-09019f54c969
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 3e163fd5-2502-47c5-9abf-c1e837262af7
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 69ca4ecc-c186-4e55-aff0-2e0875281c5b
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: 9d2e7e01-9126-4ab4-b19c-cb7b409548c7
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: d83665c8-6263-407e-9ccc-87f8e3fb5b99
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MAREKR\Documents\test_pbir\PBIBroTraining\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

